### ISSUE TITLE
Custom hotkeys/macros to run stuff

### ISSUE THREAD

**Issue by ellman12** [winggar/WingCalculator#92]
A separate GUI like this crude drawing where you can enter code for hotkeys that can be ran whenever.
![image](https://user-images.githubusercontent.com/56001219/156045455-603f3291-444b-40df-a01f-30de73dd0fd3.png)

**Comment by winggar** [comment]
done somewhere around here: b8b3145f3392b477214f3b8f5f957d58cf6c1436
