### ISSUE TITLE
Add version numbers somewhere

### ISSUE THREAD

**Issue by ellman12** [winggar/WingCalculator#98]
Preferably NOT the window title cuz that's ugly. Maybe in like a separate settings window

**Comment by winggar** [comment]
A version number has been added to the assembly, but I need to look more into MSBuild so I can put it in the program proper and auto-increment version numbers

**Comment by ellman12** [comment]
Ooooh. Sounds interesting

**Comment by winggar** [comment]
the version number can be found in the .exe's properties
