### ISSUE TITLE
Auto-add $ANS if OmniBox empty and operator like +, -, /, *, etc entered

### ISSUE THREAD

**Issue by ellman12** [winggar/WingCalculator#99]
TI calculators do this. E.g.,
Enter something like
2 + 3 = 5
then Enter, then when the Box is blank, hit the / key and input becomes
"$ANS / "

Or at least, a toggle for this somewhere

**Comment by winggar** [comment]
this already works, it just doesn't show the $ANS in the entry

**Comment by ellman12** [comment]
My bad. You can delete this issue

**Comment by winggar** [comment]
This has been added to my documentation list, though

**Comment by winggar** [comment]
I'm going to make it add $ANS to the history when $ANS is implied
